name: pytest
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - develop

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Add path for Poetry
      run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install Dependencies
      run: poetry install pytest --no-interaction
    - name: Run Tests
      run: poetry run pytest test_sample.py --cov-report=xml
      # run: poetry run pytest test --cov=./slack_api_decorator --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
# https://qiita.com/gsy0911/items/abf48168cd78ba12e199
